Header infiniband/arch.h has been deprecated, use glibc's <endian.h> instead
Use glibc's be64toh() instead of ntohll()

FYI, building mooshika with infiniband/arch.h produces the following warning and error:

  In file included from trans_rdma.c:56:0:
  /usr/include/infiniband/arch.h:37:2: error: #warning "This header is obsolete." [-Werror=cpp]
   #warning "This header is obsolete."
   ^
  trans_rdma.c: In function 'msk_print_devinfo':
  trans_rdma.c:344:2: error: 'ntohll' is deprecated (declared at /usr/include/infiniband/arch.h:44) [-Werror=deprecated-declarations]
    uint64_t node_guid = ntohll(device_attr.node_guid);